name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.2'

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        helm-version: v3.8.0

    # Authentifier avec Azure via Service Principal
    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}

    # Configurer kubeconfig pour accéder au cluster
    - name: Set up Kubeconfig from Azure
      run: |
        az aks get-credentials --resource-group plop --name 0-default --admin

    - name: Helm install or upgrade
      run: |
        helm upgrade --install flask-app ./helm-chart --namespace default --set image.repository=${{ secrets.DOCKER_USERNAME }}/flask-app,image.tag=latest

    - name: Verify deployment
      run: |
        kubectl get pods --namespace default
