name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubernetes
      uses: azure/setup-kubernetes@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        helm-version: v3.8.0

    - name: Helm install or upgrade
      run: |
        helm upgrade --install flask-app ./helm-chart --namespace default --set image.repository=${{ secrets.DOCKER_USERNAME }}/flask-app,image.tag=latest

    - name: Verify deployment
      run: |
        kubectl get pods --namespace default
