name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.2'

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        helm-version: v3.8.0

    - name: Set up Kubeconfig
      run: echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

    - name: Helm install or upgrade
      run: |
        helm upgrade --install flask-app ./helm-chart --namespace default --set image.repository=${{ secrets.DOCKER_USERNAME }}/flask-app,image.tag=latest

    - name: Verify deployment
      run: |
        kubectl get pods --namespace default
